### ISSUE TITLE
Remote access

### ISSUE THREAD

**Issue by danielducu** [deepch/RTSPtoWeb#140]
Has anyone got this working outside the network? I'm using nabu casa to access my HA...

**Comment by allenporter** [comment]
You appear to be asking about integration with home assistant.

RTSPtoWeb supports everything needed to make remote access work, however, there are two missing pieces for use in home assistant:
1) Stun server configuration in the add-on (in flight https://github.com/allenporter/stream-addons/pull/59)
2) Improvements to frontend webrtc player (in flight https://github.com/home-assistant/frontend/pull/12084)

However, since these are not really about RTSPtoWeb server itself (which already supports everything we need) we should probably move this discussion to another place.  I've made https://github.com/allenporter/stream-addons/issues/62 to track this.

**Comment by allenporter** [comment]
Also see https://github.com/deepch/RTSPtoWeb/issues/138
Duplicate issue #138
